#!/bin/sh
#
# terradeotv
#
# chkconfig: 2345 80 20
# description: Jarvis NodeJs application
# processname: Jarvis

case "$1" in
start)
 pm2 startOrRestart /home/pi/jarvis/jarvis.json
 ;;
stop)
 pm2 stop /home/pi/jarvis/jarvis.json
 ;;
status)
 pm2 list
 ;;
*)
 echo "Usage: jarvis {start|stop|status}"
 exit 1
esac
exit 0
